preprocessing:
  impedance_thr: 5e6

# config.yaml
spike_detection:
  detect_method: 'both'
  segment_duration: 5 # in minutes
  std_min: 5
  std_max: 50
  w_pre: 20
  w_post: 44
  min_ref_per: 1.5

feature_extraction:
  method: 'haar'
  haar_level: 4
  haar_ls: 64
  haar_max_inputs: 48
  haar_min_inputs: 10
  haar_nd: 10
  pca_n_components: 10

extract_waveform:
  detect_method: 'both'
  w_pre: 20
  w_post: 44
  int_factor: 5

clustering:
  plot_temperature: False
  min_temp: 0.
  max_temp: 0.251
  temp_step: 0.01
  sw_cycles: 100
  knn: 11
  min_clus: 60
  rand_seed: 0

