preprocessing:
  impedance_thr: 3000000
#  omit_channel: ['A-048', 'A-049', 'A-050', 'B-048', 'B-049', 'B-050']

# config.yaml
spike_detection:
  detect_method: 'both'
  segment_duration: 5 # in minutes
  std_min: 5
  std_max: 50
  w_pre: 20
  w_post: 44
  min_ref_per: 3
  merge_radius: 20

feature_extraction:
  method: 'spk'   # one of wav, pca, spk
  center: 20
  sigma: 5
  scales: 4
  ls: 64
  max_inputs: 0.75
  min_inputs: 10

extract_waveform:
  detect_method: 'both'
  w_pre: 20
  w_post: 44
  int_factor: 5

clustering:
  template_match:
    type: 'center'
    sdnum: 1
    k: 10
    k_min: 10
  c_ov: 0.7
  elbow_min: 0.4
  max_spk: 40000
  min_temp: 0.
  max_temp: 0.251
  temp_step: 0.1
  sw_cycles: 100
  knn: 11
  min_clus: 60
  rand_seed: 0

